name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # 1. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Build & push Docker image using the GitHub run number as the version
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Only one tag: v<run_number>, e.g. v42 if this is the 42nd run
          tags: >
            ogdmerlin/fastapi-app:v${{ github.run_number }}

      # 3. SSH to the server, pull & run the new image
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            VERSION=${{ github.run_number }}

            # Pull that same tag from Docker Hub
            docker pull ogdmerlin/fastapi-app:v$VERSION

            # Remove any old container
            docker rm -f fastapi-app || true

            # Run the new container on port 8000
            docker run -d --name fastapi-app -p 8000:8000 ogdmerlin/fastapi-app:v$VERSION

            # Reload Nginx if needed
            sudo systemctl reload nginx
